openapi: 3.0.0
info:
  title: 'BileMo API'
  description: 'This is the documention for Bilemo API.'
  version: 1.0.0
paths:
  '/api/customers/{customerId}':
    get:
      tags:
        - customer
      summary: 'Find customer by ID'
      description: 'Returns a single customer'
      operationId: 'App\Controller\CustomerController::showCustomer'
      parameters:
        -
          name: customerId
          in: path
          description: 'ID of customer to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: 'customer not found'
        '400':
          description: 'Invalid ID supplier'
    delete:
      tags:
        - customer
      summary: 'Deletes a customer'
      description: 'Delete a customer linked to a logged reseller'
      operationId: 'App\Controller\CustomerController::DeleteCustomer'
      parameters:
        -
          name: customerId
          in: path
          description: 'Customer ID to delete'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '204':
          description: 'Delete a customer'
        '404':
          description: 'Customer not found'
  /api/customers:
    get:
      tags:
        - customer
      summary: 'Find all your customers'
      description: 'Returns the list of all your customers'
      operationId: 'App\Controller\CustomerController::showCustomers'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'there is no customer for the moment'
    post:
      tags:
        - customer
      summary: 'Creates a new customer'
      description: 'Creates a new customer linked to a logged reseller'
      operationId: 'App\Controller\CustomerController::CreateCustomer'
      requestBody:
        description: 'Creates a new customer linked to a logged reseller'
        required: true
        content:
          application/json:
            schema:
              properties:
                firstname:
                  description: 'enter the firstname of the customer'
                  type: string
                lastname:
                  description: 'enter the lastname of the customer'
                  type: string
                email:
                  description: 'enter the email of the customer'
                  type: string
              type: object
              example:
                firstname: Emily
                lastname: Cooper
                email: emily.cooper@mymail.com
      responses:
        '201':
          description: 'Create a new customer'
        '400':
          description: 'Invalid input'
  '/api/phones/{phoneId}':
    get:
      tags:
        - phone
      summary: 'Find phone by ID'
      description: 'Returns a single phone'
      operationId: 'App\Controller\PhoneController::showPhone'
      parameters:
        -
          name: phoneId
          in: path
          description: 'ID of phone to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
        '404':
          description: 'Phone not found'
        '400':
          description: 'Invalid ID supplier'
  /api/phones:
    get:
      tags:
        - phone
      summary: 'Find all phones'
      description: 'Returns a list of all phones'
      operationId: 'App\Controller\PhoneController::showPhones'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'there is no phone for the moment'
  '/api/resellers/{resellerId}':
    get:
      tags:
        - reseller
      summary: 'Find reseller by ID'
      description: 'Returns a single reseller'
      operationId: 'App\Controller\ResellerController::showReseller'
      parameters:
        -
          name: resellerId
          in: path
          description: 'ID of reseller to return'
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reseller'
        '404':
          description: 'Reseller not found'
        '400':
          description: 'Invalid ID supplier'
  /api/resellers:
    get:
      tags:
        - reseller
      summary: 'Find all resellers'
      description: 'Returns a list of all resellers'
      operationId: 'App\Controller\ResellerController::showResellers'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'there is no reseller for the moment'
  /api/auth/signin:
    post:
      tags:
        - 'login and signin'
      summary: 'Signin to BileMo API'
      description: 'Signin to BileMo API'
      operationId: 'App\Controller\ResellerController::register'
      requestBody:
        description: 'enter your email and password of your choice'
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  description: 'enter your email as identifier, it must not be already taken'
                  type: string
                password:
                  description: 'enter your chosen password, minimum 8 characters, one maj, one min, one number and one special character among #?!@$ %^&*-).'
                  type: string
              type: object
              example:
                email: exemple@mymail.com
                password: mychosenpassword
      responses:
        '201':
          description: 'successful operation'
        '400':
          description: 'input is not valid'
  /api/auth/login:
    post:
      tags:
        - 'login and signin'
      summary: 'Login to BileMo API to get your token'
      description: 'This can only be done by a signed in reseller, it will let you obtain a token.'
      requestBody:
        description: 'enter your credentials'
        required: true
        content:
          application/json:
            schema:
              properties:
                username:
                  description: 'enter the email you registred with as identifier'
                  type: string
                password:
                  description: 'enter your password'
                  type: string
              type: object
              example:
                username: exemple@mymail.com
                password: mypassword
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'invalid credentials'
components:
  schemas:
    Customer:
      title: Customer
      description: 'Customer model'
      properties:
        id:
          title: ID
          description: ID
          format: int64
        firstname:
          title: Firstname
          description: 'customer Firstname'
        lastname:
          title: Lastname
          description: 'customer Lastname'
        email:
          title: Email
          description: 'customer Email'
        reseller:
          title: Reseller
          description: 'customer parent Reseller'
      type: object
    Phone:
      title: Phone
      description: 'Phone model'
      properties:
        id:
          title: ID
          description: ID
          format: int64
        brand:
          title: Brand
          description: 'phone Brand'
        model:
          title: Model
          description: 'phone Model'
        description:
          title: Description
          description: 'phone Description'
        price:
          title: Price
          description: 'phone Price'
          format: float
        internalReference:
          title: 'Internal Reference'
          description: 'phone Internal Reference'
      type: object
    Reseller:
      title: Reseller
      description: 'Reseller model'
      properties:
        email:
          title: Email
          description: 'reseller Email'
          format: string
        password:
          title: Password
          description: 'reseller password'
          type: string
          format: string
      type: object
